### ISSUE TITLE
Someone is faking your foundation in China

### ISSUE THREAD

**Issue by tonyqus** [dotnet-foundation/wg-marketing#5]
How shall I report to .NET foundation if I did notice that a group called NCC is faking your name in China?

**Comment by BethMassi** [comment]
Do you have a link to the group or other info you can share?

**Comment by tonyqus** [comment]
Website: https://www.dotnetcore.xyz/
Github: https://github.com/dotnetcore

**Comment by tonyqus** [comment]
**Evidence of faking your foundation**
a. https://archive.li/kTlN8
![image](https://user-images.githubusercontent.com/772561/96664559-a97c3600-1385-11eb-8da6-ed1372391fe9.png)

b. https://archive.li/kZ38F
![image](https://user-images.githubusercontent.com/772561/96664551-a4b78200-1385-11eb-9ccb-652a9785179a.png)

c. https://archive.li/OjIhH
![image](https://user-images.githubusercontent.com/772561/96664542-9cf7dd80-1385-11eb-8df0-17471a0d0e8e.png)

d. https://archive.li/wAs5U
![image](https://user-images.githubusercontent.com/772561/96664532-979a9300-1385-11eb-8880-2cf85cbc6dda.png)


So far, the original pages are still available and the page view is huge. I'm not sure if they are on purpose or not. Or it's savorboard's personal behavior.

**Comment by tonyqus** [comment]
Did you give authorization to this group before to be on behalf of your foundation in China? They looks to be official and on behalf of Microsoft. Not only the name but also what they say in the blog and offline event. [Savorboard](https://github.com/yang-xiaodong) is a senior member of this NCC group. He is the owner of [Dotnetcore/CAP](https://github.com/dotnetcore/cap) and [Dotnetcore/NPOI](https://github.com/dotnetcore/npoi). 

I didn't know the organization well until they block me from Dotnetcore/NPOI last month and they attract my attention. Then I start full investigation of this semi-official .NET open source group.

**Comment by BethMassi** [comment]
Ah. Yes we are aware and working with Microsoft on this. Thanks for reporting. This is not a group endorsed by either Microsoft or .NET Foundation.

**Comment by jonechenug** [comment]
Aslo the [dotnet-cn](https://github.com/dotnet-cn)  is a impostor.They has not any opensource code project!

**Comment by jamiehowarth0** [comment]
I've been discussing this extensively with @tonyqus, as the group has also broken an OSS license by not providing correct copyright attribution on their fork of NPOI.

@BethMassi I sent you & @clairernovotny an email about a week ago regarding this, not sure if you got it?

**Comment by clairernovotny** [comment]
Can't comment publicly on this issue, sorry.

**Comment by tonyqus** [comment]
@clairernovotny Sure, no problem. 

I'm still investigating this NCC org.  According to the evidence I collected, I can conclude their mind/ideas as below

1. If you are maintaining the project personally instead of joining NCC, your open source project cannot be used in commercial cases.
2. If we NCC reject you to join us as a member project or you don't want to join,  your project is nothing and we can clone your project as we want because we are official and professional. After we renaming/branding it under NCC, it can be more glorious and perfect. 
3. Only NCC can do open source projects. Other open source contributors/orgnizations are nothing or not officially allowed to do contribution to .NET community in China. Because NCC are .NET China Foundation.

These conclusion are based on real evidences. I'm a bit worrying that they are brainwashed by themselves or they listened to some evil Bible. The logic from them are very weird. I only have seen this kind of statement or ideas in some evil churchs. 

I'm preparing an article about this and it will be published to the public soon. I totally understand what kind of danger I'm facing after publishing this article. Anyway, my lawyer is ready for this. Although China's law may NOT protect people from cyber-bullying in most cases, I can still make sure that no one can threat me for free speech. I have to defense basic developer rights to contribute to the .NET community in China and worldwide, not only for me but also for the other developers in China.

**Comment by johnwiichang** [comment]
The .NET Core Community originated from a .NET study group. NCC describes itself as an "unofficial" organization, and does not claim any association with Microsoft or the .NET Foundation. This organization is a regional interest technology organization, driven by the open source community. In addition, the .NET technology stack is driven by the .NET Foundation.

You might think that the .NET Core community is very close to the .NET community, but you can't think of the relationship between the two. Just like Java and JavaScript, you can't think of this as a scripted version of Java.

> .NET Core Community (means .net's central community, referred to as NCC) is an unofficial, non-profit open source community based on the .NET technology stack.

Several Microsoft most valuable professional (MVP) and important Chinese .NET developers participated in the construction of NCC. As the supporters of .NET, we know that opening up a working ecosystem of .NET in the wasteland of .NET in China depends on every Chinese developer. As the NCC active in the Chinese community, its outstanding contribution to this is worthy of recognition.

In addition, according to the widespread NPOI incident, I hope that it will not be resolved in the form of dashing to a tower(a MOA words). NCC has issued a notice to close the controversial warehouse and is expected to delete the release version on Nuget.org. Although we developers regret the demise of the .NET Core branch of such a friendly NPOI, we still thank NCC. It is because of their spare efforts that we can find a familiar feeling on the brand new platform of .NET Core.

**Comment by johnwiichang** [comment]
The .NET Core Community originated from a .NET study group. NCC describes itself as an "unofficial" organization, and does not claim any association with Microsoft or the .NET Foundation. This organization is a regional interest technology organisation, driven by the open source community. In addition, the .NET technology stack is driven by the .NET Foundation **NOT MICROSOFT**.

> .NET is bigger than just Microsoft and we want to see the platform survive for another 20 years – in the open. We want to collaborate with industry partners that will innovate with the **community**.

You might think that the .NET Core Community is very close to the .NET Foundation, but you can't think of the relationship between the two. Just like Java and JavaScript, you can't think of this as a scripted version of Java. **NCC is a community**, not a foundation:

> .NET Core **Community** (means .net's central **community**, referred to as NCC) is an unofficial, non-profit open source **community** based on the .NET technology stack.

And Several Microsoft Most Valuable Professional (MVP) and important Chinese .NET developers participated in the construction of NCC. As the supporters of .NET, we know that opening up a working ecosystem of .NET in the wasteland of .NET in China depends on every Chinese developer. As the NCC active in the Chinese community, its outstanding contribution to this is worthy of recognition.

In addition, according to the widespread NPOI incident, I hope that it will not be resolved in the form of dashing to a tower(a MOA words). NCC has issued a notice to close the controversial warehouse and is expected to delete the release version on Nuget.org. Although we developers regret the demise of the .NET Core branch of such a friendly NPOI, we still thank NCC. It is because of their spare efforts that we can find a familiar feeling on the brand new platform of .NET Core.

Let us revisit our standards:

> **Our Standards**
> 
> Examples of behavior that contributes to a positive environment for our community include:
>    · **Demonstrating empathy and kindness toward other people**
>    · **Being respectful of differing opinions, viewpoints, and experiences**
>    · **Giving and gracefully accepting constructive feedback**
>    · Accepting responsibility and apologising to those affected by our mistakes, and learning from the experience
>    · **Focusing on what is best not just for us as individuals, but for the overall community**
>
> Examples of unacceptable behaviour include:
>    · The use of sexualised language or imagery, and sexual attention or advances of any kind
>    · Trolling, insulting or derogatory comments, and personal or political attacks
>    · Public or private harassment
>    · Publishing others’ private information, such as a physical or email address, without their explicit permission
>    · Other conduct which could reasonably be considered inappropriate in a professional setting

**Comment by Rwing** [comment]
I'm a unorganized .net developer in China and  I don't agree with tonyqus, please don't represent me.
I think this is personal grudge between you and NPOI, please don't influence other developers or organizations.
And as far as I know, there are some things you are lying about, so please don't be evil.

**Comment by survivalguide** [comment]
I'm on @tonyqus 's side. The organization name (dotnetcore) is confusing a lot of developers . 
Why they do not use the name of dotnetcoreCommunity ? 

In fact, the current name can easily be mistaken for a MICROSOFT official organization. 
IF they are .NET Core Community organization ,I suggest they change the name which is not so strange.
IF you guys think thats OK, Can anyone also register an organization called just like `Microsoft-Edge` and claim unofficial ? Is that OK ?

I know that many developers mistakenly think this is the official dotnetcore account. 
In addition, the certified URL mentioned in the introduction which has a Verified label is also easy to be misunderstood for its officiality.

![image](https://user-images.githubusercontent.com/62740537/97403249-0ef49780-192f-11eb-8fb6-4a0258abc6be.png)

**Comment by johnwiichang** [comment]
> I'm on @tonyqus 's side. The organization name (dotnetcore) is confusing a lot of developers .
> Why they do not use the name of dotnetcoreCommunity ?
> 
> In fact, the current name can easily be mistaken for a MICROSOFT official organization.
> IF they are .NET Core Community organization ,I suggest they change the name which is not so strange.
> IF you guys think thats OK, Can anyone also register an organization called just like `Microsoft-Edge` and claim unofficial ? Is that OK ?
> 
> I know that many developers mistakenly think this is the official dotnetcore account.
> In addition, the certified URL mentioned in the introduction which has a Verified label is also easy to be misunderstood for its officiality.
> 
> ![image](https://user-images.githubusercontent.com/62740537/97403249-0ef49780-192f-11eb-8fb6-4a0258abc6be.png)

First of all, .NET is driven by the community and Microsoft is just a contributor. **The statement that Microsoft's official .NET account is contrary to the spirit of .NET itself**.
Second, the mission of the NCC goes hand in hand with the community mission proposed by the foundation.
Finally, Microsoft Edge is the name of a **commercial product**, but .NET is a community-driven technology stack. **It is not called Microsoft .NET** (_Microsoft has spent so much effort to get rid of Microsoft, I hope you can see it_).

**Comment by johnwiichang** [comment]
It is a pity to see the lineage argument about "Microsoft Official". .NET is a technical term rather than a commercial product. In the past, many arguments criticized .NET as saying that this is a technology controlled by Microsoft. This has blocked the development of .NET technology in some countries and regions (because they regard Microsoft as a scourge).
Yes, we have to admit that Microsoft's contribution to .NET is indelible, but Microsoft also declared that .NET is a community project. Cooperation and joint construction can expand the .NET ecosystem. NCC has not violated the foundation organization and is well-known in the Chinese .NET ecosystem.
If it is said that the name change due to NCC's implied meaning of "Microsoft ancestry" may cause the open source community to question and ridicule ".NET is a community-driven project", and the argument of "Microsoft-controlled technology" may re-emerge.

---

In addition, products like ClickHouse also have their own Chinese communities, and they even directly registered top-level domain names like **clickhouse.com.cn**. I hope that all .NET enthusiasts will not indulge in such political struggles, carry forward the spirit of the .NET Foundation and the spirit of open source, and jointly develop the .NET ecosystem.

**Comment by prkhandelwal** [comment]
I think we are missing the main point of here! IF the community is question is in any way causing any confusion among developers (accidently or intentionally), something needs to be done to fix that. Although the page clearly mentions "unofficial", I think the people arguing how their branding can make people think it's an official account have a fair point.

I came across NCC's page a while ago while searching for .NET Core repo, and if I didn't know any better, I would have easily confused it for an official account. If the handle is implying that to developers in any way, I hope the NCC folks will do something about it keeping developers' & .NET's best interests in mind.

**Comment by jamiehowarth0** [comment]
> I think we are missing the main point of here! IF the community is question is in any way causing any confusion among developers (accidently or intentionally), something needs to be done to fix that. Although the page clearly mentions "unofficial", I think the people arguing how their branding can make people think it's an official account have a fair point.
> 
> I came across NCC's page a while ago while searching for .NET Core repo, and if I didn't know any better, I would have easily confused it for an official account. If the handle is implying that to developers in any way, I hope the NCC folks will do something about it keeping developers' & .NET's best interests in mind.

NCC's deliberate use of colour scheme & .NET's name (used in organisation name on Github, and domain name) can result in confusion as to whether NCC is officially part of the Foundation's efforts.

As a member of .NET Foundation, and given @clairernovotny & @BethMassi's remarks, I cannot make any legally-binding statements on behalf of the Foundation. Clearly, the Foundation & Microsoft are exploring avenues & will be following up with the appropriate parties involved.

However, personally (speaking as an individual), I believe that that confusion has been deliberately exploited by NCC - by using the branding, colour scheme & naming, they have attempted to appropriate some sort of "official" status without actually having legally requested permission, or joined into the Foundation & requesting use of IP marks in the correct fashion. I personally believe that NCC has used misrepresentation to garner support and money - and in the UK, where I live, that is a form of fraud.

Note: I am not accusing NCC of a crime. I am, however, stating the facts regarding use of marks, branding, and calling into question it's legality.

Edit: prior to this all kicking off, I discovered that NCC had forked @tonyqus NPOI project to help support .NET Core. However, in the forking process, NCC had removed any credit to @tonyqus, which is a direct breach of the original NPOI OSS license.
I would find it extremely difficult to work with any contributors from any country who claim genuine intent, who are also happy to actively and publicly break open-source license terms. This breaks not only a legally-binding license, but also the moral code of the open-source community. I would therefore question anybody from NCC wanting to "validate" their community without first asking why they broke the legal & moral code that helps the .NET ecosystem to exist in the first place.

**Comment by clairernovotny** [comment]
I'm going to lock this for now. We're looking into it and there's not much more we can say on the matter right now.
