### ISSUE TITLE
Does dotnet-cn job is  real ?

### ISSUE THREAD

**Issue by jonechenug** [dotnet-foundation/wg-marketing#6]
I found a project  [dotnet-cn](https://github.com/dotnet-cn),there is a [job](https://github.com/dotnet-cn/jobs) repository.
It is seductive , how many big companies !

**Comment by BethMassi** [comment]
Closing this issue as I don't see anything actionable for the marketing committee here. Feel free to open another issue if there is something you're specifically asking us to do.

**Comment by tonyqus** [comment]
Sorry for the confusion that @jonechenug brought you half a year ago. You are somewhat right. You don't speak Chinese and you don't want to touch this case.  I'll handle these guys. Don't worry.

The good news is that  I keep updateing dotnet-cn/jobs during the past half year in order to let more developers know that .NET is not dying. A lot of companies are still using .NET in China although most of them are MNC or traditional industry companies.  

In the last round of .NET to java techical stack conversion, a lot of big companies abandon .NET as the primary programming language. It's a shame and somewhat failure of .NET marketing in China. I think It's time to change it. I'm planning something to make it happen. Let's see.

**Comment by tonyqus** [comment]
**Some updates**

After 4 years, https://github.com/dotnet-cn/jobs is still updating. 

I'm also maintaining a new repo https://github.com/tonyqus/dotnet-jobs-my/ since I've moved to Malaysia.

The methodology is same. Both repos are based on real hiring in major job websites such as Indeed, Linkedin, JobStreet and so on.
